
# Go base image 
FROM golang:1.24.3

# working directory 
WORKDIR /app

# copy go mod files and download dependencies 
COPY  go.mod go.sum ./

# Download dependencies
RUN go mod download

# copy application source code
COPY . . 

# Build the app binary
RUN go build -o drones_data_collector

# Create persistent data directory
RUN mkdir -p /data && chmod a+rw /data
VOLUME /data

# MISCONFIGURATION: Hardcoded Secrets
ENV API_KEY="secret_key_12345"

# MISCONFIGURATION: Insecure Permissions
RUN mkdir -p /data && chmod 777 /data
VOLUME /data

# ---------------------------------------------------------
# NEW MISCONFIGURATION: Exposing Insecure/Privileged Ports
# ---------------------------------------------------------
# Port 22 
EXPOSE 22 
# Port 80 
EXPOSE 80


# RUN the app
CMD [ "./drones_data_collector" ]